### ISSUE TITLE
simultaneousGesture will disable button action

### ISSUE THREAD

**Issue by SouHanaQiao** [divadretlaw/CustomAlert#11] opened 2023-11-16 03:12 UTC
`      .simultaneousGesture(TapGesture().onEnded { _ in
            guard isEnabled else { return }
            isPresented = false
        })`
this will disable button action

**Comment by divadretlaw** [comment] 2023-11-16 16:29
Thank you for reporting this issue. I have found the cause and it should be fixed in `3.0.3`

**Closed** 2023-11-20 22:09 UTC
